name: Autoupdating blocklist.txt

on:
  schedule:
    - cron: "0 0 1 * *"
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - name: setup nodejs
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        npm u npm
        npm i -g @adguard/hostlist-compiler
    - name: update blocklist
      run: | 
          echo "generate config.json"
          python ./update.py
          echo "make adguard home's blocklist"
          hostlist-compiler -c config-block.json -v -o blocklist.txt
          # Remove Headers & Comments
          temp=$(mktemp)
          cat blocklist.txt | sed '/#/d' | sed '/!/d' > $temp
          # Remove Blank/Empty Lines
          sed '/^$/d' -i $temp
          mv $temp blocklist.txt
